module Geolocation
  module Utils
    HTTP_SERVICE_UNAVAILABLE = 503
    HTTP_NOT_FOUND = 404
    HTTP_OK = 200
    HTTP_CREATED = 201
    HTTP_NO_CONTENT = 204
    HTTP_UNPROCESSABLE_ENTITY = 422
  end
end
